// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATYd3Oe9MVjaF1XXhcRNZPetIT488tups',
    appId: '1:489795118019:web:7263e8e32ce4144e861376',
    messagingSenderId: '489795118019',
    projectId: 'ders-proje-467e0',
    authDomain: 'ders-proje-467e0.firebaseapp.com',
    storageBucket: 'ders-proje-467e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYKBBE8s0pX3_XIeuj-A7oq8hZqNx0Rmo',
    appId: '1:489795118019:android:84ad9ebb53957f19861376',
    messagingSenderId: '489795118019',
    projectId: 'ders-proje-467e0',
    storageBucket: 'ders-proje-467e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGgsxVHI8TdrLR1Ju72wfrzBM-Ya_HiKY',
    appId: '1:489795118019:ios:681a699ece0af4e0861376',
    messagingSenderId: '489795118019',
    projectId: 'ders-proje-467e0',
    storageBucket: 'ders-proje-467e0.appspot.com',
    iosClientId: '489795118019-pmi5crd7p3n7be5ktabrc8apg270g31m.apps.googleusercontent.com',
    iosBundleId: 'com.example.dersProje',
  );
}
